language: java
dist: trusty
script: gradle build
deploy:
  provider: releases
  api_key:
    secure: ZCcrG6dAo+KzvctAZHiZgrXncspe0+eyMZel3k0xGHjQyklcebnNDkdAv+uljKqEdbBXr8Yr6FPVSR8WPi6B/ZK5d4a9LwPJD8NfRmOqbYgf5ZgBo/K4DguzqjWBAtap7jhautDkHPlMGgtxKTKa8wr+XGZX7fC6TQ//HLB5JVFp9eVZ8W7HkgvXCf7VY/51V5NpS0p1vAvK9FdbtIiGibCZ6hErlQLKnGdm/uSaU4Xv0vJTmo7JDn2Asu+cN0ys/wvkG9H78d0onJqrzIlFENrvFiLhN7wswRFKIl6oNy8W10EvmF8Wjz2/5V5gkXX8l8FkFIipOcSD3LkSdRryGKg9EJckwuaQ37XVdlZPWDlseJEalrVtAogzPQidlFN9TAr//UeCvvpUkZkW6xu5SVDjIC/Zk3TWHu01LquTE4C1JBNAlpvgO6157r/X3w/cfvTv+w7Qouiq1fIBK3HEWyI077QVbWzkX+jxaEvuYtJWX3S3C6oV0GE/QWdoyFyiSZcGyh9BRlJXI2YYnKElkLrp4swozEAnHXFTdI5zMbtuDbw3OEU4X3I8kt8DV3RiNDMjqYGHzaaWgRRndDwcvQ7SuwD3hweiNcpPaM3EPtOBOFSg0zBv8RkUqqhBCwdlTJbgEG2YPiVcHARBIW99E16C+IUMh+W+nSW/XRdZdq8=
  file: build/libs/mewpoke*
  skip_cleanup: true
  on:
    tag: true
