app:
  measurementPeriodInSec: 10
  refreshDiscoveryPeriodInSec: 60
  httpServerPort: 8080

discovery:
  consul:
    host: consul.service.consul
    port: 8500
    timeoutInSec: 10
    readConsistency: STALE
    tags:
      - bucket-Core.Services.Test.Cache

service:
  type: MEMCACHED_INJECTOR
  timeoutInSec: 60
